### ISSUE TITLE
Exception handling does not follow C# guideline

### ISSUE THREAD

**Issue by m4cx** [hassanhabib/EFxceptions#3]
In the past we all followed [Microsoft's design guideline regarding exception handling](https://docs.microsoft.com/en-us/previous-versions/dotnet/netframework-4.0/ms229005(v=vs.100)). I'm wondering if it still applies to .NET Core / .NET Standard.

If so, you might be hiding information or make it harder to find the root cause.

[Let me show you an example:](https://github.com/hassanhabib/EFxceptions/blob/a7f1ac077cc69656a7ca0d65e48c0501d04f05b1/EFxceptions/EFxceptionsContext.cs#L26)
```csharp
public override async Task<int> SaveChangesAsync(CancellationToken cancellationToken = default)
{
    try
    {
        return await base.SaveChangesAsync(cancellationToken);
    }
    catch (DbUpdateException dbUpdateException)
    {
        this.eFxceptionService.ThrowMeaningfulException(dbUpdateException);
        throw dbUpdateException; // <-- That's the problem
        throw; // <-- would be better
    }
}
```

**Comment by hassanhabib** [comment]
@m4cx that's a good point, it really depends on whether we want to throw the entire stack trace since the beginning of the operation or just the exception that we intend to throw, in this case, we are simply giving back ```dbUpdateException``` once the ```ThrowMeaningfulException``` can't find any mapping for the SQL inner exception error code.

**Comment by m4cx** [comment]
@hassanhabib Since you are neither really doing sth. different than the original ```SaveChangesAsync()``` call nor really handling the exception if no mapping is found, I would say you would be better of rethrowing the original exception with the complete stack trace. Or do you have any other things you want to accomplish that hasn't been written down yet?

**Comment by hassanhabib** [comment]
@m4cx not really, I think you're making a good point, will have that addressed, I appreciate the feedback.
